// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auto_interface.proto
#ifndef GRPC_auto_5finterface_2eproto__INCLUDED
#define GRPC_auto_5finterface_2eproto__INCLUDED

#include "auto_interface.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace autointerface {

class AutoInterface final {
 public:
  static constexpr char const* service_full_name() {
    return "autointerface.AutoInterface";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::HelloRequest, ::autointerface::HelloRequest>> SayHello(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::HelloRequest, ::autointerface::HelloRequest>>(SayHelloRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::HelloRequest, ::autointerface::HelloRequest>> AsyncSayHello(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::HelloRequest, ::autointerface::HelloRequest>>(AsyncSayHelloRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::HelloRequest, ::autointerface::HelloRequest>> PrepareAsyncSayHello(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::HelloRequest, ::autointerface::HelloRequest>>(PrepareAsyncSayHelloRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>> SayHellog(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>>(SayHellogRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>> AsyncSayHellog(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>>(AsyncSayHellogRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>> PrepareAsyncSayHellog(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>>(PrepareAsyncSayHellogRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>> SayHelloh(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>>(SayHellohRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>> AsyncSayHelloh(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>>(AsyncSayHellohRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>> PrepareAsyncSayHelloh(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>>(PrepareAsyncSayHellohRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>> SayHelloq(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>>(SayHelloqRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>> AsyncSayHelloq(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>>(AsyncSayHelloqRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>> PrepareAsyncSayHelloq(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>>(PrepareAsyncSayHelloqRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>> SayHelloOtherVehicleData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>>(SayHelloOtherVehicleDataRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>> AsyncSayHelloOtherVehicleData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>>(AsyncSayHelloOtherVehicleDataRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>> PrepareAsyncSayHelloOtherVehicleData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>>(PrepareAsyncSayHelloOtherVehicleDataRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>> SayHelloPacketOtherVehicleDatalist(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>>(SayHelloPacketOtherVehicleDatalistRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>> AsyncSayHelloPacketOtherVehicleDatalist(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>>(AsyncSayHelloPacketOtherVehicleDatalistRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>> PrepareAsyncSayHelloPacketOtherVehicleDatalist(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>>(PrepareAsyncSayHelloPacketOtherVehicleDatalistRaw(context, cq));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* SayHelloRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* AsyncSayHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* SayHellogRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* AsyncSayHellogRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* PrepareAsyncSayHellogRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* SayHellohRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* AsyncSayHellohRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* PrepareAsyncSayHellohRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* SayHelloqRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* AsyncSayHelloqRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* PrepareAsyncSayHelloqRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* SayHelloOtherVehicleDataRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* AsyncSayHelloOtherVehicleDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* PrepareAsyncSayHelloOtherVehicleDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* SayHelloPacketOtherVehicleDatalistRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* AsyncSayHelloPacketOtherVehicleDatalistRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* PrepareAsyncSayHelloPacketOtherVehicleDatalistRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>> SayHello(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>>(SayHelloRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>> AsyncSayHello(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>>(AsyncSayHelloRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>> PrepareAsyncSayHello(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>>(PrepareAsyncSayHelloRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>> SayHellog(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>>(SayHellogRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>> AsyncSayHellog(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>>(AsyncSayHellogRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>> PrepareAsyncSayHellog(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>>(PrepareAsyncSayHellogRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>> SayHelloh(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>>(SayHellohRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>> AsyncSayHelloh(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>>(AsyncSayHellohRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>> PrepareAsyncSayHelloh(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>>(PrepareAsyncSayHellohRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>> SayHelloq(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>>(SayHelloqRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>> AsyncSayHelloq(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>>(AsyncSayHelloqRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>> PrepareAsyncSayHelloq(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>>(PrepareAsyncSayHelloqRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>> SayHelloOtherVehicleData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>>(SayHelloOtherVehicleDataRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>> AsyncSayHelloOtherVehicleData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>>(AsyncSayHelloOtherVehicleDataRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>> PrepareAsyncSayHelloOtherVehicleData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>>(PrepareAsyncSayHelloOtherVehicleDataRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>> SayHelloPacketOtherVehicleDatalist(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>>(SayHelloPacketOtherVehicleDatalistRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>> AsyncSayHelloPacketOtherVehicleDatalist(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>>(AsyncSayHelloPacketOtherVehicleDatalistRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>> PrepareAsyncSayHelloPacketOtherVehicleDatalist(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>>(PrepareAsyncSayHelloPacketOtherVehicleDatalistRaw(context, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* SayHelloRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* AsyncSayHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* SayHellogRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* AsyncSayHellogRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* PrepareAsyncSayHellogRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* SayHellohRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* AsyncSayHellohRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* PrepareAsyncSayHellohRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* SayHelloqRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* AsyncSayHelloqRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* PrepareAsyncSayHelloqRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* SayHelloOtherVehicleDataRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* AsyncSayHelloOtherVehicleDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* PrepareAsyncSayHelloOtherVehicleDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* SayHelloPacketOtherVehicleDatalistRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* AsyncSayHelloPacketOtherVehicleDatalistRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* PrepareAsyncSayHelloPacketOtherVehicleDatalistRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
    const ::grpc::internal::RpcMethod rpcmethod_SayHellog_;
    const ::grpc::internal::RpcMethod rpcmethod_SayHelloh_;
    const ::grpc::internal::RpcMethod rpcmethod_SayHelloq_;
    const ::grpc::internal::RpcMethod rpcmethod_SayHelloOtherVehicleData_;
    const ::grpc::internal::RpcMethod rpcmethod_SayHelloPacketOtherVehicleDatalist_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* stream);
    virtual ::grpc::Status SayHellog(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* stream);
    virtual ::grpc::Status SayHelloh(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* stream);
    virtual ::grpc::Status SayHelloq(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* stream);
    virtual ::grpc::Status SayHelloOtherVehicleData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* stream);
    virtual ::grpc::Status SayHelloPacketOtherVehicleDatalist(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHellog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SayHellog() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SayHellog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHellog(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHellog(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHelloh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SayHelloh() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SayHelloh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloh(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHelloh(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHelloq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SayHelloq() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_SayHelloq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloq(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHelloq(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHelloOtherVehicleData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SayHelloOtherVehicleData() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_SayHelloOtherVehicleData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloOtherVehicleData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHelloOtherVehicleData(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(4, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHelloPacketOtherVehicleDatalist : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SayHelloPacketOtherVehicleDatalist() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_SayHelloPacketOtherVehicleDatalist() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloPacketOtherVehicleDatalist(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHelloPacketOtherVehicleDatalist(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(5, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<WithAsyncMethod_SayHellog<WithAsyncMethod_SayHelloh<WithAsyncMethod_SayHelloq<WithAsyncMethod_SayHelloOtherVehicleData<WithAsyncMethod_SayHelloPacketOtherVehicleDatalist<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SayHellog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SayHellog() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SayHellog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHellog(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SayHelloh : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SayHelloh() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SayHelloh() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloh(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SayHelloq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SayHelloq() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_SayHelloq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloq(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SayHelloOtherVehicleData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SayHelloOtherVehicleData() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_SayHelloOtherVehicleData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloOtherVehicleData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SayHelloPacketOtherVehicleDatalist : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SayHelloPacketOtherVehicleDatalist() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_SayHelloPacketOtherVehicleDatalist() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHelloPacketOtherVehicleDatalist(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace autointerface


#endif  // GRPC_auto_5finterface_2eproto__INCLUDED
