// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auto_interface.proto

#ifndef PROTOBUF_auto_5finterface_2eproto__INCLUDED
#define PROTOBUF_auto_5finterface_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_auto_5finterface_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsHelloRequestImpl();
void InitDefaultsHelloRequest();
void InitDefaultsaPacketReckonImpl();
void InitDefaultsaPacketReckon();
void InitDefaultsaPacketCanMsgImpl();
void InitDefaultsaPacketCanMsg();
void InitDefaultsaPacketIbeoVectorImpl();
void InitDefaultsaPacketIbeoVector();
void InitDefaultsaOtherVehicleDataImpl();
void InitDefaultsaOtherVehicleData();
void InitDefaultsaPacketOtherVehicleDatalistImpl();
void InitDefaultsaPacketOtherVehicleDatalist();
inline void InitDefaults() {
  InitDefaultsHelloRequest();
  InitDefaultsaPacketReckon();
  InitDefaultsaPacketCanMsg();
  InitDefaultsaPacketIbeoVector();
  InitDefaultsaOtherVehicleData();
  InitDefaultsaPacketOtherVehicleDatalist();
}
}  // namespace protobuf_auto_5finterface_2eproto
namespace autointerface {
class HelloRequest;
class HelloRequestDefaultTypeInternal;
extern HelloRequestDefaultTypeInternal _HelloRequest_default_instance_;
class aOtherVehicleData;
class aOtherVehicleDataDefaultTypeInternal;
extern aOtherVehicleDataDefaultTypeInternal _aOtherVehicleData_default_instance_;
class aPacketCanMsg;
class aPacketCanMsgDefaultTypeInternal;
extern aPacketCanMsgDefaultTypeInternal _aPacketCanMsg_default_instance_;
class aPacketIbeoVector;
class aPacketIbeoVectorDefaultTypeInternal;
extern aPacketIbeoVectorDefaultTypeInternal _aPacketIbeoVector_default_instance_;
class aPacketOtherVehicleDatalist;
class aPacketOtherVehicleDatalistDefaultTypeInternal;
extern aPacketOtherVehicleDatalistDefaultTypeInternal _aPacketOtherVehicleDatalist_default_instance_;
class aPacketReckon;
class aPacketReckonDefaultTypeInternal;
extern aPacketReckonDefaultTypeInternal _aPacketReckon_default_instance_;
}  // namespace autointerface
namespace autointerface {

// ===================================================================

class HelloRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:autointerface.HelloRequest) */ {
 public:
  HelloRequest();
  virtual ~HelloRequest();

  HelloRequest(const HelloRequest& from);

  inline HelloRequest& operator=(const HelloRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HelloRequest(HelloRequest&& from) noexcept
    : HelloRequest() {
    *this = ::std::move(from);
  }

  inline HelloRequest& operator=(HelloRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HelloRequest* internal_default_instance() {
    return reinterpret_cast<const HelloRequest*>(
               &_HelloRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(HelloRequest* other);
  friend void swap(HelloRequest& a, HelloRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HelloRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  HelloRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HelloRequest& from);
  void MergeFrom(const HelloRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HelloRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 lengthOfPlan = 1;
  void clear_lengthofplan();
  static const int kLengthOfPlanFieldNumber = 1;
  ::google::protobuf::int32 lengthofplan() const;
  void set_lengthofplan(::google::protobuf::int32 value);

  // float lanelx = 2;
  void clear_lanelx();
  static const int kLanelxFieldNumber = 2;
  float lanelx() const;
  void set_lanelx(float value);

  // float lanely = 3;
  void clear_lanely();
  static const int kLanelyFieldNumber = 3;
  float lanely() const;
  void set_lanely(float value);

  // float StopLaneDis = 4;
  void clear_stoplanedis();
  static const int kStopLaneDisFieldNumber = 4;
  float stoplanedis() const;
  void set_stoplanedis(float value);

  // float pathPoints = 5;
  void clear_pathpoints();
  static const int kPathPointsFieldNumber = 5;
  float pathpoints() const;
  void set_pathpoints(float value);

  // float pathPointx = 6;
  void clear_pathpointx();
  static const int kPathPointxFieldNumber = 6;
  float pathpointx() const;
  void set_pathpointx(float value);

  // @@protoc_insertion_point(class_scope:autointerface.HelloRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 lengthofplan_;
  float lanelx_;
  float lanely_;
  float stoplanedis_;
  float pathpoints_;
  float pathpointx_;
  mutable int _cached_size_;
  friend struct ::protobuf_auto_5finterface_2eproto::TableStruct;
  friend void ::protobuf_auto_5finterface_2eproto::InitDefaultsHelloRequestImpl();
};
// -------------------------------------------------------------------

class aPacketReckon : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:autointerface.aPacketReckon) */ {
 public:
  aPacketReckon();
  virtual ~aPacketReckon();

  aPacketReckon(const aPacketReckon& from);

  inline aPacketReckon& operator=(const aPacketReckon& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  aPacketReckon(aPacketReckon&& from) noexcept
    : aPacketReckon() {
    *this = ::std::move(from);
  }

  inline aPacketReckon& operator=(aPacketReckon&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const aPacketReckon& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const aPacketReckon* internal_default_instance() {
    return reinterpret_cast<const aPacketReckon*>(
               &_aPacketReckon_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(aPacketReckon* other);
  friend void swap(aPacketReckon& a, aPacketReckon& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline aPacketReckon* New() const PROTOBUF_FINAL { return New(NULL); }

  aPacketReckon* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const aPacketReckon& from);
  void MergeFrom(const aPacketReckon& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(aPacketReckon* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float dX = 1;
  void clear_dx();
  static const int kDXFieldNumber = 1;
  float dx() const;
  void set_dx(float value);

  // float dY = 2;
  void clear_dy();
  static const int kDYFieldNumber = 2;
  float dy() const;
  void set_dy(float value);

  // float dThe = 3;
  void clear_dthe();
  static const int kDTheFieldNumber = 3;
  float dthe() const;
  void set_dthe(float value);

  // @@protoc_insertion_point(class_scope:autointerface.aPacketReckon)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float dx_;
  float dy_;
  float dthe_;
  mutable int _cached_size_;
  friend struct ::protobuf_auto_5finterface_2eproto::TableStruct;
  friend void ::protobuf_auto_5finterface_2eproto::InitDefaultsaPacketReckonImpl();
};
// -------------------------------------------------------------------

class aPacketCanMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:autointerface.aPacketCanMsg) */ {
 public:
  aPacketCanMsg();
  virtual ~aPacketCanMsg();

  aPacketCanMsg(const aPacketCanMsg& from);

  inline aPacketCanMsg& operator=(const aPacketCanMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  aPacketCanMsg(aPacketCanMsg&& from) noexcept
    : aPacketCanMsg() {
    *this = ::std::move(from);
  }

  inline aPacketCanMsg& operator=(aPacketCanMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const aPacketCanMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const aPacketCanMsg* internal_default_instance() {
    return reinterpret_cast<const aPacketCanMsg*>(
               &_aPacketCanMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(aPacketCanMsg* other);
  friend void swap(aPacketCanMsg& a, aPacketCanMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline aPacketCanMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  aPacketCanMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const aPacketCanMsg& from);
  void MergeFrom(const aPacketCanMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(aPacketCanMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .autointerface.aPacketReckon reckon = 9;
  bool has_reckon() const;
  void clear_reckon();
  static const int kReckonFieldNumber = 9;
  const ::autointerface::aPacketReckon& reckon() const;
  ::autointerface::aPacketReckon* release_reckon();
  ::autointerface::aPacketReckon* mutable_reckon();
  void set_allocated_reckon(::autointerface::aPacketReckon* reckon);

  // float steer = 1;
  void clear_steer();
  static const int kSteerFieldNumber = 1;
  float steer() const;
  void set_steer(float value);

  // float speed = 2;
  void clear_speed();
  static const int kSpeedFieldNumber = 2;
  float speed() const;
  void set_speed(float value);

  // int32 gearPos = 3;
  void clear_gearpos();
  static const int kGearPosFieldNumber = 3;
  ::google::protobuf::int32 gearpos() const;
  void set_gearpos(::google::protobuf::int32 value);

  // int32 EPB_status = 4;
  void clear_epb_status();
  static const int kEPBStatusFieldNumber = 4;
  ::google::protobuf::int32 epb_status() const;
  void set_epb_status(::google::protobuf::int32 value);

  // int32 EHB_Pressure = 5;
  void clear_ehb_pressure();
  static const int kEHBPressureFieldNumber = 5;
  ::google::protobuf::int32 ehb_pressure() const;
  void set_ehb_pressure(::google::protobuf::int32 value);

  // float sonicx = 6;
  void clear_sonicx();
  static const int kSonicxFieldNumber = 6;
  float sonicx() const;
  void set_sonicx(float value);

  // float sonicy = 7;
  void clear_sonicy();
  static const int kSonicyFieldNumber = 7;
  float sonicy() const;
  void set_sonicy(float value);

  // int32 rawdis = 8;
  void clear_rawdis();
  static const int kRawdisFieldNumber = 8;
  ::google::protobuf::int32 rawdis() const;
  void set_rawdis(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:autointerface.aPacketCanMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::autointerface::aPacketReckon* reckon_;
  float steer_;
  float speed_;
  ::google::protobuf::int32 gearpos_;
  ::google::protobuf::int32 epb_status_;
  ::google::protobuf::int32 ehb_pressure_;
  float sonicx_;
  float sonicy_;
  ::google::protobuf::int32 rawdis_;
  mutable int _cached_size_;
  friend struct ::protobuf_auto_5finterface_2eproto::TableStruct;
  friend void ::protobuf_auto_5finterface_2eproto::InitDefaultsaPacketCanMsgImpl();
};
// -------------------------------------------------------------------

class aPacketIbeoVector : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:autointerface.aPacketIbeoVector) */ {
 public:
  aPacketIbeoVector();
  virtual ~aPacketIbeoVector();

  aPacketIbeoVector(const aPacketIbeoVector& from);

  inline aPacketIbeoVector& operator=(const aPacketIbeoVector& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  aPacketIbeoVector(aPacketIbeoVector&& from) noexcept
    : aPacketIbeoVector() {
    *this = ::std::move(from);
  }

  inline aPacketIbeoVector& operator=(aPacketIbeoVector&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const aPacketIbeoVector& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const aPacketIbeoVector* internal_default_instance() {
    return reinterpret_cast<const aPacketIbeoVector*>(
               &_aPacketIbeoVector_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(aPacketIbeoVector* other);
  friend void swap(aPacketIbeoVector& a, aPacketIbeoVector& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline aPacketIbeoVector* New() const PROTOBUF_FINAL { return New(NULL); }

  aPacketIbeoVector* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const aPacketIbeoVector& from);
  void MergeFrom(const aPacketIbeoVector& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(aPacketIbeoVector* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float ibcontourx = 13;
  int ibcontourx_size() const;
  void clear_ibcontourx();
  static const int kIbcontourxFieldNumber = 13;
  float ibcontourx(int index) const;
  void set_ibcontourx(int index, float value);
  void add_ibcontourx(float value);
  const ::google::protobuf::RepeatedField< float >&
      ibcontourx() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_ibcontourx();

  // repeated float ibcontoury = 14;
  int ibcontoury_size() const;
  void clear_ibcontoury();
  static const int kIbcontouryFieldNumber = 14;
  float ibcontoury(int index) const;
  void set_ibcontoury(int index, float value);
  void add_ibcontoury(float value);
  const ::google::protobuf::RepeatedField< float >&
      ibcontoury() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_ibcontoury();

  // int32 index = 1;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // int32 lengthOfObject = 2;
  void clear_lengthofobject();
  static const int kLengthOfObjectFieldNumber = 2;
  ::google::protobuf::int32 lengthofobject() const;
  void set_lengthofobject(::google::protobuf::int32 value);

  // int32 lengthOfContour = 3;
  void clear_lengthofcontour();
  static const int kLengthOfContourFieldNumber = 3;
  ::google::protobuf::int32 lengthofcontour() const;
  void set_lengthofcontour(::google::protobuf::int32 value);

  // float ibx = 4;
  void clear_ibx();
  static const int kIbxFieldNumber = 4;
  float ibx() const;
  void set_ibx(float value);

  // float iby = 5;
  void clear_iby();
  static const int kIbyFieldNumber = 5;
  float iby() const;
  void set_iby(float value);

  // float ibw = 6;
  void clear_ibw();
  static const int kIbwFieldNumber = 6;
  float ibw() const;
  void set_ibw(float value);

  // float ibl = 7;
  void clear_ibl();
  static const int kIblFieldNumber = 7;
  float ibl() const;
  void set_ibl(float value);

  // float ibvx = 8;
  void clear_ibvx();
  static const int kIbvxFieldNumber = 8;
  float ibvx() const;
  void set_ibvx(float value);

  // float ibvy = 9;
  void clear_ibvy();
  static const int kIbvyFieldNumber = 9;
  float ibvy() const;
  void set_ibvy(float value);

  // float ibvabx = 10;
  void clear_ibvabx();
  static const int kIbvabxFieldNumber = 10;
  float ibvabx() const;
  void set_ibvabx(float value);

  // float ibvaby = 11;
  void clear_ibvaby();
  static const int kIbvabyFieldNumber = 11;
  float ibvaby() const;
  void set_ibvaby(float value);

  // int32 ibcontournum = 12;
  void clear_ibcontournum();
  static const int kIbcontournumFieldNumber = 12;
  ::google::protobuf::int32 ibcontournum() const;
  void set_ibcontournum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:autointerface.aPacketIbeoVector)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > ibcontourx_;
  mutable int _ibcontourx_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > ibcontoury_;
  mutable int _ibcontoury_cached_byte_size_;
  ::google::protobuf::int32 index_;
  ::google::protobuf::int32 lengthofobject_;
  ::google::protobuf::int32 lengthofcontour_;
  float ibx_;
  float iby_;
  float ibw_;
  float ibl_;
  float ibvx_;
  float ibvy_;
  float ibvabx_;
  float ibvaby_;
  ::google::protobuf::int32 ibcontournum_;
  mutable int _cached_size_;
  friend struct ::protobuf_auto_5finterface_2eproto::TableStruct;
  friend void ::protobuf_auto_5finterface_2eproto::InitDefaultsaPacketIbeoVectorImpl();
};
// -------------------------------------------------------------------

class aOtherVehicleData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:autointerface.aOtherVehicleData) */ {
 public:
  aOtherVehicleData();
  virtual ~aOtherVehicleData();

  aOtherVehicleData(const aOtherVehicleData& from);

  inline aOtherVehicleData& operator=(const aOtherVehicleData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  aOtherVehicleData(aOtherVehicleData&& from) noexcept
    : aOtherVehicleData() {
    *this = ::std::move(from);
  }

  inline aOtherVehicleData& operator=(aOtherVehicleData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const aOtherVehicleData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const aOtherVehicleData* internal_default_instance() {
    return reinterpret_cast<const aOtherVehicleData*>(
               &_aOtherVehicleData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(aOtherVehicleData* other);
  friend void swap(aOtherVehicleData& a, aOtherVehicleData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline aOtherVehicleData* New() const PROTOBUF_FINAL { return New(NULL); }

  aOtherVehicleData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const aOtherVehicleData& from);
  void MergeFrom(const aOtherVehicleData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(aOtherVehicleData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 stationID = 1;
  void clear_stationid();
  static const int kStationIDFieldNumber = 1;
  ::google::protobuf::int32 stationid() const;
  void set_stationid(::google::protobuf::int32 value);

  // float accuracy = 2;
  void clear_accuracy();
  static const int kAccuracyFieldNumber = 2;
  float accuracy() const;
  void set_accuracy(float value);

  // double lat = 3;
  void clear_lat();
  static const int kLatFieldNumber = 3;
  double lat() const;
  void set_lat(double value);

  // double lon = 4;
  void clear_lon();
  static const int kLonFieldNumber = 4;
  double lon() const;
  void set_lon(double value);

  // double heading = 5;
  void clear_heading();
  static const int kHeadingFieldNumber = 5;
  double heading() const;
  void set_heading(double value);

  // double referenceTime = 7;
  void clear_referencetime();
  static const int kReferenceTimeFieldNumber = 7;
  double referencetime() const;
  void set_referencetime(double value);

  // double longitudinalAcceleration = 8;
  void clear_longitudinalacceleration();
  static const int kLongitudinalAccelerationFieldNumber = 8;
  double longitudinalacceleration() const;
  void set_longitudinalacceleration(double value);

  // float speed = 6;
  void clear_speed();
  static const int kSpeedFieldNumber = 6;
  float speed() const;
  void set_speed(float value);

  // int32 platoonID = 10;
  void clear_platoonid();
  static const int kPlatoonIDFieldNumber = 10;
  ::google::protobuf::int32 platoonid() const;
  void set_platoonid(::google::protobuf::int32 value);

  // double lateralAcceleration = 9;
  void clear_lateralacceleration();
  static const int kLateralAccelerationFieldNumber = 9;
  double lateralacceleration() const;
  void set_lateralacceleration(double value);

  // int32 posInPlatoon = 11;
  void clear_posinplatoon();
  static const int kPosInPlatoonFieldNumber = 11;
  ::google::protobuf::int32 posinplatoon() const;
  void set_posinplatoon(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:autointerface.aOtherVehicleData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 stationid_;
  float accuracy_;
  double lat_;
  double lon_;
  double heading_;
  double referencetime_;
  double longitudinalacceleration_;
  float speed_;
  ::google::protobuf::int32 platoonid_;
  double lateralacceleration_;
  ::google::protobuf::int32 posinplatoon_;
  mutable int _cached_size_;
  friend struct ::protobuf_auto_5finterface_2eproto::TableStruct;
  friend void ::protobuf_auto_5finterface_2eproto::InitDefaultsaOtherVehicleDataImpl();
};
// -------------------------------------------------------------------

class aPacketOtherVehicleDatalist : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:autointerface.aPacketOtherVehicleDatalist) */ {
 public:
  aPacketOtherVehicleDatalist();
  virtual ~aPacketOtherVehicleDatalist();

  aPacketOtherVehicleDatalist(const aPacketOtherVehicleDatalist& from);

  inline aPacketOtherVehicleDatalist& operator=(const aPacketOtherVehicleDatalist& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  aPacketOtherVehicleDatalist(aPacketOtherVehicleDatalist&& from) noexcept
    : aPacketOtherVehicleDatalist() {
    *this = ::std::move(from);
  }

  inline aPacketOtherVehicleDatalist& operator=(aPacketOtherVehicleDatalist&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const aPacketOtherVehicleDatalist& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const aPacketOtherVehicleDatalist* internal_default_instance() {
    return reinterpret_cast<const aPacketOtherVehicleDatalist*>(
               &_aPacketOtherVehicleDatalist_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(aPacketOtherVehicleDatalist* other);
  friend void swap(aPacketOtherVehicleDatalist& a, aPacketOtherVehicleDatalist& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline aPacketOtherVehicleDatalist* New() const PROTOBUF_FINAL { return New(NULL); }

  aPacketOtherVehicleDatalist* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const aPacketOtherVehicleDatalist& from);
  void MergeFrom(const aPacketOtherVehicleDatalist& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(aPacketOtherVehicleDatalist* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .autointerface.aOtherVehicleData vehicle = 2;
  bool has_vehicle() const;
  void clear_vehicle();
  static const int kVehicleFieldNumber = 2;
  const ::autointerface::aOtherVehicleData& vehicle() const;
  ::autointerface::aOtherVehicleData* release_vehicle();
  ::autointerface::aOtherVehicleData* mutable_vehicle();
  void set_allocated_vehicle(::autointerface::aOtherVehicleData* vehicle);

  // int32 numOfVehicles = 1;
  void clear_numofvehicles();
  static const int kNumOfVehiclesFieldNumber = 1;
  ::google::protobuf::int32 numofvehicles() const;
  void set_numofvehicles(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:autointerface.aPacketOtherVehicleDatalist)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::autointerface::aOtherVehicleData* vehicle_;
  ::google::protobuf::int32 numofvehicles_;
  mutable int _cached_size_;
  friend struct ::protobuf_auto_5finterface_2eproto::TableStruct;
  friend void ::protobuf_auto_5finterface_2eproto::InitDefaultsaPacketOtherVehicleDatalistImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HelloRequest

// int32 lengthOfPlan = 1;
inline void HelloRequest::clear_lengthofplan() {
  lengthofplan_ = 0;
}
inline ::google::protobuf::int32 HelloRequest::lengthofplan() const {
  // @@protoc_insertion_point(field_get:autointerface.HelloRequest.lengthOfPlan)
  return lengthofplan_;
}
inline void HelloRequest::set_lengthofplan(::google::protobuf::int32 value) {
  
  lengthofplan_ = value;
  // @@protoc_insertion_point(field_set:autointerface.HelloRequest.lengthOfPlan)
}

// float lanelx = 2;
inline void HelloRequest::clear_lanelx() {
  lanelx_ = 0;
}
inline float HelloRequest::lanelx() const {
  // @@protoc_insertion_point(field_get:autointerface.HelloRequest.lanelx)
  return lanelx_;
}
inline void HelloRequest::set_lanelx(float value) {
  
  lanelx_ = value;
  // @@protoc_insertion_point(field_set:autointerface.HelloRequest.lanelx)
}

// float lanely = 3;
inline void HelloRequest::clear_lanely() {
  lanely_ = 0;
}
inline float HelloRequest::lanely() const {
  // @@protoc_insertion_point(field_get:autointerface.HelloRequest.lanely)
  return lanely_;
}
inline void HelloRequest::set_lanely(float value) {
  
  lanely_ = value;
  // @@protoc_insertion_point(field_set:autointerface.HelloRequest.lanely)
}

// float StopLaneDis = 4;
inline void HelloRequest::clear_stoplanedis() {
  stoplanedis_ = 0;
}
inline float HelloRequest::stoplanedis() const {
  // @@protoc_insertion_point(field_get:autointerface.HelloRequest.StopLaneDis)
  return stoplanedis_;
}
inline void HelloRequest::set_stoplanedis(float value) {
  
  stoplanedis_ = value;
  // @@protoc_insertion_point(field_set:autointerface.HelloRequest.StopLaneDis)
}

// float pathPoints = 5;
inline void HelloRequest::clear_pathpoints() {
  pathpoints_ = 0;
}
inline float HelloRequest::pathpoints() const {
  // @@protoc_insertion_point(field_get:autointerface.HelloRequest.pathPoints)
  return pathpoints_;
}
inline void HelloRequest::set_pathpoints(float value) {
  
  pathpoints_ = value;
  // @@protoc_insertion_point(field_set:autointerface.HelloRequest.pathPoints)
}

// float pathPointx = 6;
inline void HelloRequest::clear_pathpointx() {
  pathpointx_ = 0;
}
inline float HelloRequest::pathpointx() const {
  // @@protoc_insertion_point(field_get:autointerface.HelloRequest.pathPointx)
  return pathpointx_;
}
inline void HelloRequest::set_pathpointx(float value) {
  
  pathpointx_ = value;
  // @@protoc_insertion_point(field_set:autointerface.HelloRequest.pathPointx)
}

// -------------------------------------------------------------------

// aPacketReckon

// float dX = 1;
inline void aPacketReckon::clear_dx() {
  dx_ = 0;
}
inline float aPacketReckon::dx() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketReckon.dX)
  return dx_;
}
inline void aPacketReckon::set_dx(float value) {
  
  dx_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketReckon.dX)
}

// float dY = 2;
inline void aPacketReckon::clear_dy() {
  dy_ = 0;
}
inline float aPacketReckon::dy() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketReckon.dY)
  return dy_;
}
inline void aPacketReckon::set_dy(float value) {
  
  dy_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketReckon.dY)
}

// float dThe = 3;
inline void aPacketReckon::clear_dthe() {
  dthe_ = 0;
}
inline float aPacketReckon::dthe() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketReckon.dThe)
  return dthe_;
}
inline void aPacketReckon::set_dthe(float value) {
  
  dthe_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketReckon.dThe)
}

// -------------------------------------------------------------------

// aPacketCanMsg

// float steer = 1;
inline void aPacketCanMsg::clear_steer() {
  steer_ = 0;
}
inline float aPacketCanMsg::steer() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketCanMsg.steer)
  return steer_;
}
inline void aPacketCanMsg::set_steer(float value) {
  
  steer_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketCanMsg.steer)
}

// float speed = 2;
inline void aPacketCanMsg::clear_speed() {
  speed_ = 0;
}
inline float aPacketCanMsg::speed() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketCanMsg.speed)
  return speed_;
}
inline void aPacketCanMsg::set_speed(float value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketCanMsg.speed)
}

// int32 gearPos = 3;
inline void aPacketCanMsg::clear_gearpos() {
  gearpos_ = 0;
}
inline ::google::protobuf::int32 aPacketCanMsg::gearpos() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketCanMsg.gearPos)
  return gearpos_;
}
inline void aPacketCanMsg::set_gearpos(::google::protobuf::int32 value) {
  
  gearpos_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketCanMsg.gearPos)
}

// int32 EPB_status = 4;
inline void aPacketCanMsg::clear_epb_status() {
  epb_status_ = 0;
}
inline ::google::protobuf::int32 aPacketCanMsg::epb_status() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketCanMsg.EPB_status)
  return epb_status_;
}
inline void aPacketCanMsg::set_epb_status(::google::protobuf::int32 value) {
  
  epb_status_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketCanMsg.EPB_status)
}

// int32 EHB_Pressure = 5;
inline void aPacketCanMsg::clear_ehb_pressure() {
  ehb_pressure_ = 0;
}
inline ::google::protobuf::int32 aPacketCanMsg::ehb_pressure() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketCanMsg.EHB_Pressure)
  return ehb_pressure_;
}
inline void aPacketCanMsg::set_ehb_pressure(::google::protobuf::int32 value) {
  
  ehb_pressure_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketCanMsg.EHB_Pressure)
}

// float sonicx = 6;
inline void aPacketCanMsg::clear_sonicx() {
  sonicx_ = 0;
}
inline float aPacketCanMsg::sonicx() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketCanMsg.sonicx)
  return sonicx_;
}
inline void aPacketCanMsg::set_sonicx(float value) {
  
  sonicx_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketCanMsg.sonicx)
}

// float sonicy = 7;
inline void aPacketCanMsg::clear_sonicy() {
  sonicy_ = 0;
}
inline float aPacketCanMsg::sonicy() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketCanMsg.sonicy)
  return sonicy_;
}
inline void aPacketCanMsg::set_sonicy(float value) {
  
  sonicy_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketCanMsg.sonicy)
}

// int32 rawdis = 8;
inline void aPacketCanMsg::clear_rawdis() {
  rawdis_ = 0;
}
inline ::google::protobuf::int32 aPacketCanMsg::rawdis() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketCanMsg.rawdis)
  return rawdis_;
}
inline void aPacketCanMsg::set_rawdis(::google::protobuf::int32 value) {
  
  rawdis_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketCanMsg.rawdis)
}

// .autointerface.aPacketReckon reckon = 9;
inline bool aPacketCanMsg::has_reckon() const {
  return this != internal_default_instance() && reckon_ != NULL;
}
inline void aPacketCanMsg::clear_reckon() {
  if (GetArenaNoVirtual() == NULL && reckon_ != NULL) {
    delete reckon_;
  }
  reckon_ = NULL;
}
inline const ::autointerface::aPacketReckon& aPacketCanMsg::reckon() const {
  const ::autointerface::aPacketReckon* p = reckon_;
  // @@protoc_insertion_point(field_get:autointerface.aPacketCanMsg.reckon)
  return p != NULL ? *p : *reinterpret_cast<const ::autointerface::aPacketReckon*>(
      &::autointerface::_aPacketReckon_default_instance_);
}
inline ::autointerface::aPacketReckon* aPacketCanMsg::release_reckon() {
  // @@protoc_insertion_point(field_release:autointerface.aPacketCanMsg.reckon)
  
  ::autointerface::aPacketReckon* temp = reckon_;
  reckon_ = NULL;
  return temp;
}
inline ::autointerface::aPacketReckon* aPacketCanMsg::mutable_reckon() {
  
  if (reckon_ == NULL) {
    reckon_ = new ::autointerface::aPacketReckon;
  }
  // @@protoc_insertion_point(field_mutable:autointerface.aPacketCanMsg.reckon)
  return reckon_;
}
inline void aPacketCanMsg::set_allocated_reckon(::autointerface::aPacketReckon* reckon) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reckon_;
  }
  if (reckon) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      reckon = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, reckon, submessage_arena);
    }
    
  } else {
    
  }
  reckon_ = reckon;
  // @@protoc_insertion_point(field_set_allocated:autointerface.aPacketCanMsg.reckon)
}

// -------------------------------------------------------------------

// aPacketIbeoVector

// int32 index = 1;
inline void aPacketIbeoVector::clear_index() {
  index_ = 0;
}
inline ::google::protobuf::int32 aPacketIbeoVector::index() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.index)
  return index_;
}
inline void aPacketIbeoVector::set_index(::google::protobuf::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.index)
}

// int32 lengthOfObject = 2;
inline void aPacketIbeoVector::clear_lengthofobject() {
  lengthofobject_ = 0;
}
inline ::google::protobuf::int32 aPacketIbeoVector::lengthofobject() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.lengthOfObject)
  return lengthofobject_;
}
inline void aPacketIbeoVector::set_lengthofobject(::google::protobuf::int32 value) {
  
  lengthofobject_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.lengthOfObject)
}

// int32 lengthOfContour = 3;
inline void aPacketIbeoVector::clear_lengthofcontour() {
  lengthofcontour_ = 0;
}
inline ::google::protobuf::int32 aPacketIbeoVector::lengthofcontour() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.lengthOfContour)
  return lengthofcontour_;
}
inline void aPacketIbeoVector::set_lengthofcontour(::google::protobuf::int32 value) {
  
  lengthofcontour_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.lengthOfContour)
}

// float ibx = 4;
inline void aPacketIbeoVector::clear_ibx() {
  ibx_ = 0;
}
inline float aPacketIbeoVector::ibx() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibx)
  return ibx_;
}
inline void aPacketIbeoVector::set_ibx(float value) {
  
  ibx_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibx)
}

// float iby = 5;
inline void aPacketIbeoVector::clear_iby() {
  iby_ = 0;
}
inline float aPacketIbeoVector::iby() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.iby)
  return iby_;
}
inline void aPacketIbeoVector::set_iby(float value) {
  
  iby_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.iby)
}

// float ibw = 6;
inline void aPacketIbeoVector::clear_ibw() {
  ibw_ = 0;
}
inline float aPacketIbeoVector::ibw() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibw)
  return ibw_;
}
inline void aPacketIbeoVector::set_ibw(float value) {
  
  ibw_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibw)
}

// float ibl = 7;
inline void aPacketIbeoVector::clear_ibl() {
  ibl_ = 0;
}
inline float aPacketIbeoVector::ibl() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibl)
  return ibl_;
}
inline void aPacketIbeoVector::set_ibl(float value) {
  
  ibl_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibl)
}

// float ibvx = 8;
inline void aPacketIbeoVector::clear_ibvx() {
  ibvx_ = 0;
}
inline float aPacketIbeoVector::ibvx() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibvx)
  return ibvx_;
}
inline void aPacketIbeoVector::set_ibvx(float value) {
  
  ibvx_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibvx)
}

// float ibvy = 9;
inline void aPacketIbeoVector::clear_ibvy() {
  ibvy_ = 0;
}
inline float aPacketIbeoVector::ibvy() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibvy)
  return ibvy_;
}
inline void aPacketIbeoVector::set_ibvy(float value) {
  
  ibvy_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibvy)
}

// float ibvabx = 10;
inline void aPacketIbeoVector::clear_ibvabx() {
  ibvabx_ = 0;
}
inline float aPacketIbeoVector::ibvabx() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibvabx)
  return ibvabx_;
}
inline void aPacketIbeoVector::set_ibvabx(float value) {
  
  ibvabx_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibvabx)
}

// float ibvaby = 11;
inline void aPacketIbeoVector::clear_ibvaby() {
  ibvaby_ = 0;
}
inline float aPacketIbeoVector::ibvaby() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibvaby)
  return ibvaby_;
}
inline void aPacketIbeoVector::set_ibvaby(float value) {
  
  ibvaby_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibvaby)
}

// int32 ibcontournum = 12;
inline void aPacketIbeoVector::clear_ibcontournum() {
  ibcontournum_ = 0;
}
inline ::google::protobuf::int32 aPacketIbeoVector::ibcontournum() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibcontournum)
  return ibcontournum_;
}
inline void aPacketIbeoVector::set_ibcontournum(::google::protobuf::int32 value) {
  
  ibcontournum_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibcontournum)
}

// repeated float ibcontourx = 13;
inline int aPacketIbeoVector::ibcontourx_size() const {
  return ibcontourx_.size();
}
inline void aPacketIbeoVector::clear_ibcontourx() {
  ibcontourx_.Clear();
}
inline float aPacketIbeoVector::ibcontourx(int index) const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibcontourx)
  return ibcontourx_.Get(index);
}
inline void aPacketIbeoVector::set_ibcontourx(int index, float value) {
  ibcontourx_.Set(index, value);
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibcontourx)
}
inline void aPacketIbeoVector::add_ibcontourx(float value) {
  ibcontourx_.Add(value);
  // @@protoc_insertion_point(field_add:autointerface.aPacketIbeoVector.ibcontourx)
}
inline const ::google::protobuf::RepeatedField< float >&
aPacketIbeoVector::ibcontourx() const {
  // @@protoc_insertion_point(field_list:autointerface.aPacketIbeoVector.ibcontourx)
  return ibcontourx_;
}
inline ::google::protobuf::RepeatedField< float >*
aPacketIbeoVector::mutable_ibcontourx() {
  // @@protoc_insertion_point(field_mutable_list:autointerface.aPacketIbeoVector.ibcontourx)
  return &ibcontourx_;
}

// repeated float ibcontoury = 14;
inline int aPacketIbeoVector::ibcontoury_size() const {
  return ibcontoury_.size();
}
inline void aPacketIbeoVector::clear_ibcontoury() {
  ibcontoury_.Clear();
}
inline float aPacketIbeoVector::ibcontoury(int index) const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketIbeoVector.ibcontoury)
  return ibcontoury_.Get(index);
}
inline void aPacketIbeoVector::set_ibcontoury(int index, float value) {
  ibcontoury_.Set(index, value);
  // @@protoc_insertion_point(field_set:autointerface.aPacketIbeoVector.ibcontoury)
}
inline void aPacketIbeoVector::add_ibcontoury(float value) {
  ibcontoury_.Add(value);
  // @@protoc_insertion_point(field_add:autointerface.aPacketIbeoVector.ibcontoury)
}
inline const ::google::protobuf::RepeatedField< float >&
aPacketIbeoVector::ibcontoury() const {
  // @@protoc_insertion_point(field_list:autointerface.aPacketIbeoVector.ibcontoury)
  return ibcontoury_;
}
inline ::google::protobuf::RepeatedField< float >*
aPacketIbeoVector::mutable_ibcontoury() {
  // @@protoc_insertion_point(field_mutable_list:autointerface.aPacketIbeoVector.ibcontoury)
  return &ibcontoury_;
}

// -------------------------------------------------------------------

// aOtherVehicleData

// int32 stationID = 1;
inline void aOtherVehicleData::clear_stationid() {
  stationid_ = 0;
}
inline ::google::protobuf::int32 aOtherVehicleData::stationid() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.stationID)
  return stationid_;
}
inline void aOtherVehicleData::set_stationid(::google::protobuf::int32 value) {
  
  stationid_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.stationID)
}

// float accuracy = 2;
inline void aOtherVehicleData::clear_accuracy() {
  accuracy_ = 0;
}
inline float aOtherVehicleData::accuracy() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.accuracy)
  return accuracy_;
}
inline void aOtherVehicleData::set_accuracy(float value) {
  
  accuracy_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.accuracy)
}

// double lat = 3;
inline void aOtherVehicleData::clear_lat() {
  lat_ = 0;
}
inline double aOtherVehicleData::lat() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.lat)
  return lat_;
}
inline void aOtherVehicleData::set_lat(double value) {
  
  lat_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.lat)
}

// double lon = 4;
inline void aOtherVehicleData::clear_lon() {
  lon_ = 0;
}
inline double aOtherVehicleData::lon() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.lon)
  return lon_;
}
inline void aOtherVehicleData::set_lon(double value) {
  
  lon_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.lon)
}

// double heading = 5;
inline void aOtherVehicleData::clear_heading() {
  heading_ = 0;
}
inline double aOtherVehicleData::heading() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.heading)
  return heading_;
}
inline void aOtherVehicleData::set_heading(double value) {
  
  heading_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.heading)
}

// float speed = 6;
inline void aOtherVehicleData::clear_speed() {
  speed_ = 0;
}
inline float aOtherVehicleData::speed() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.speed)
  return speed_;
}
inline void aOtherVehicleData::set_speed(float value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.speed)
}

// double referenceTime = 7;
inline void aOtherVehicleData::clear_referencetime() {
  referencetime_ = 0;
}
inline double aOtherVehicleData::referencetime() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.referenceTime)
  return referencetime_;
}
inline void aOtherVehicleData::set_referencetime(double value) {
  
  referencetime_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.referenceTime)
}

// double longitudinalAcceleration = 8;
inline void aOtherVehicleData::clear_longitudinalacceleration() {
  longitudinalacceleration_ = 0;
}
inline double aOtherVehicleData::longitudinalacceleration() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.longitudinalAcceleration)
  return longitudinalacceleration_;
}
inline void aOtherVehicleData::set_longitudinalacceleration(double value) {
  
  longitudinalacceleration_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.longitudinalAcceleration)
}

// double lateralAcceleration = 9;
inline void aOtherVehicleData::clear_lateralacceleration() {
  lateralacceleration_ = 0;
}
inline double aOtherVehicleData::lateralacceleration() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.lateralAcceleration)
  return lateralacceleration_;
}
inline void aOtherVehicleData::set_lateralacceleration(double value) {
  
  lateralacceleration_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.lateralAcceleration)
}

// int32 platoonID = 10;
inline void aOtherVehicleData::clear_platoonid() {
  platoonid_ = 0;
}
inline ::google::protobuf::int32 aOtherVehicleData::platoonid() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.platoonID)
  return platoonid_;
}
inline void aOtherVehicleData::set_platoonid(::google::protobuf::int32 value) {
  
  platoonid_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.platoonID)
}

// int32 posInPlatoon = 11;
inline void aOtherVehicleData::clear_posinplatoon() {
  posinplatoon_ = 0;
}
inline ::google::protobuf::int32 aOtherVehicleData::posinplatoon() const {
  // @@protoc_insertion_point(field_get:autointerface.aOtherVehicleData.posInPlatoon)
  return posinplatoon_;
}
inline void aOtherVehicleData::set_posinplatoon(::google::protobuf::int32 value) {
  
  posinplatoon_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aOtherVehicleData.posInPlatoon)
}

// -------------------------------------------------------------------

// aPacketOtherVehicleDatalist

// int32 numOfVehicles = 1;
inline void aPacketOtherVehicleDatalist::clear_numofvehicles() {
  numofvehicles_ = 0;
}
inline ::google::protobuf::int32 aPacketOtherVehicleDatalist::numofvehicles() const {
  // @@protoc_insertion_point(field_get:autointerface.aPacketOtherVehicleDatalist.numOfVehicles)
  return numofvehicles_;
}
inline void aPacketOtherVehicleDatalist::set_numofvehicles(::google::protobuf::int32 value) {
  
  numofvehicles_ = value;
  // @@protoc_insertion_point(field_set:autointerface.aPacketOtherVehicleDatalist.numOfVehicles)
}

// .autointerface.aOtherVehicleData vehicle = 2;
inline bool aPacketOtherVehicleDatalist::has_vehicle() const {
  return this != internal_default_instance() && vehicle_ != NULL;
}
inline void aPacketOtherVehicleDatalist::clear_vehicle() {
  if (GetArenaNoVirtual() == NULL && vehicle_ != NULL) {
    delete vehicle_;
  }
  vehicle_ = NULL;
}
inline const ::autointerface::aOtherVehicleData& aPacketOtherVehicleDatalist::vehicle() const {
  const ::autointerface::aOtherVehicleData* p = vehicle_;
  // @@protoc_insertion_point(field_get:autointerface.aPacketOtherVehicleDatalist.vehicle)
  return p != NULL ? *p : *reinterpret_cast<const ::autointerface::aOtherVehicleData*>(
      &::autointerface::_aOtherVehicleData_default_instance_);
}
inline ::autointerface::aOtherVehicleData* aPacketOtherVehicleDatalist::release_vehicle() {
  // @@protoc_insertion_point(field_release:autointerface.aPacketOtherVehicleDatalist.vehicle)
  
  ::autointerface::aOtherVehicleData* temp = vehicle_;
  vehicle_ = NULL;
  return temp;
}
inline ::autointerface::aOtherVehicleData* aPacketOtherVehicleDatalist::mutable_vehicle() {
  
  if (vehicle_ == NULL) {
    vehicle_ = new ::autointerface::aOtherVehicleData;
  }
  // @@protoc_insertion_point(field_mutable:autointerface.aPacketOtherVehicleDatalist.vehicle)
  return vehicle_;
}
inline void aPacketOtherVehicleDatalist::set_allocated_vehicle(::autointerface::aOtherVehicleData* vehicle) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete vehicle_;
  }
  if (vehicle) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      vehicle = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, vehicle, submessage_arena);
    }
    
  } else {
    
  }
  vehicle_ = vehicle;
  // @@protoc_insertion_point(field_set_allocated:autointerface.aPacketOtherVehicleDatalist.vehicle)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace autointerface

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_auto_5finterface_2eproto__INCLUDED
