// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auto_interface.proto

#include "auto_interface.pb.h"
#include "auto_interface.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace autointerface {

static const char* AutoInterface_method_names[] = {
  "/autointerface.AutoInterface/SayHello",
  "/autointerface.AutoInterface/SayHellog",
  "/autointerface.AutoInterface/SayHelloh",
  "/autointerface.AutoInterface/SayHelloq",
  "/autointerface.AutoInterface/SayHelloOtherVehicleData",
  "/autointerface.AutoInterface/SayHelloPacketOtherVehicleDatalist",
};

std::unique_ptr< AutoInterface::Stub> AutoInterface::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< AutoInterface::Stub> stub(new AutoInterface::Stub(channel));
  return stub;
}

AutoInterface::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(AutoInterface_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_SayHellog_(AutoInterface_method_names[1], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_SayHelloh_(AutoInterface_method_names[2], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_SayHelloq_(AutoInterface_method_names[3], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_SayHelloOtherVehicleData_(AutoInterface_method_names[4], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_SayHelloPacketOtherVehicleDatalist_(AutoInterface_method_names[5], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* AutoInterface::Stub::SayHelloRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::autointerface::HelloRequest, ::autointerface::HelloRequest>::Create(channel_.get(), rpcmethod_SayHello_, context);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* AutoInterface::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::HelloRequest, ::autointerface::HelloRequest>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* AutoInterface::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::HelloRequest, ::autointerface::HelloRequest>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* AutoInterface::Stub::SayHellogRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>::Create(channel_.get(), rpcmethod_SayHellog_, context);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* AutoInterface::Stub::AsyncSayHellogRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>::Create(channel_.get(), cq, rpcmethod_SayHellog_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* AutoInterface::Stub::PrepareAsyncSayHellogRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>::Create(channel_.get(), cq, rpcmethod_SayHellog_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* AutoInterface::Stub::SayHellohRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>::Create(channel_.get(), rpcmethod_SayHelloh_, context);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* AutoInterface::Stub::AsyncSayHellohRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>::Create(channel_.get(), cq, rpcmethod_SayHelloh_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* AutoInterface::Stub::PrepareAsyncSayHellohRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>::Create(channel_.get(), cq, rpcmethod_SayHelloh_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* AutoInterface::Stub::SayHelloqRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>::Create(channel_.get(), rpcmethod_SayHelloq_, context);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* AutoInterface::Stub::AsyncSayHelloqRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>::Create(channel_.get(), cq, rpcmethod_SayHelloq_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* AutoInterface::Stub::PrepareAsyncSayHelloqRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>::Create(channel_.get(), cq, rpcmethod_SayHelloq_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* AutoInterface::Stub::SayHelloOtherVehicleDataRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>::Create(channel_.get(), rpcmethod_SayHelloOtherVehicleData_, context);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* AutoInterface::Stub::AsyncSayHelloOtherVehicleDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>::Create(channel_.get(), cq, rpcmethod_SayHelloOtherVehicleData_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* AutoInterface::Stub::PrepareAsyncSayHelloOtherVehicleDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>::Create(channel_.get(), cq, rpcmethod_SayHelloOtherVehicleData_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* AutoInterface::Stub::SayHelloPacketOtherVehicleDatalistRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>::Create(channel_.get(), rpcmethod_SayHelloPacketOtherVehicleDatalist_, context);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* AutoInterface::Stub::AsyncSayHelloPacketOtherVehicleDatalistRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>::Create(channel_.get(), cq, rpcmethod_SayHelloPacketOtherVehicleDatalist_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* AutoInterface::Stub::PrepareAsyncSayHelloPacketOtherVehicleDatalistRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>::Create(channel_.get(), cq, rpcmethod_SayHelloPacketOtherVehicleDatalist_, context, false, nullptr);
}

AutoInterface::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AutoInterface_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< AutoInterface::Service, ::autointerface::HelloRequest, ::autointerface::HelloRequest>(
          std::mem_fn(&AutoInterface::Service::SayHello), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AutoInterface_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< AutoInterface::Service, ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>(
          std::mem_fn(&AutoInterface::Service::SayHellog), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AutoInterface_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< AutoInterface::Service, ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>(
          std::mem_fn(&AutoInterface::Service::SayHelloh), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AutoInterface_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< AutoInterface::Service, ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>(
          std::mem_fn(&AutoInterface::Service::SayHelloq), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AutoInterface_method_names[4],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< AutoInterface::Service, ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>(
          std::mem_fn(&AutoInterface::Service::SayHelloOtherVehicleData), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AutoInterface_method_names[5],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< AutoInterface::Service, ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>(
          std::mem_fn(&AutoInterface::Service::SayHelloPacketOtherVehicleDatalist), this)));
}

AutoInterface::Service::~Service() {
}

::grpc::Status AutoInterface::Service::SayHello(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::HelloRequest, ::autointerface::HelloRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AutoInterface::Service::SayHellog(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketReckon, ::autointerface::aPacketReckon>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AutoInterface::Service::SayHelloh(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketCanMsg, ::autointerface::aPacketCanMsg>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AutoInterface::Service::SayHelloq(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketIbeoVector, ::autointerface::aPacketIbeoVector>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AutoInterface::Service::SayHelloOtherVehicleData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aOtherVehicleData, ::autointerface::aOtherVehicleData>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AutoInterface::Service::SayHelloPacketOtherVehicleDatalist(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::autointerface::aPacketOtherVehicleDatalist, ::autointerface::aPacketOtherVehicleDatalist>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace autointerface

